### PR TITLE
minor change

### PR DESCRIPTION
**Pull request by Pub4Game**
minor change

### CODE REVIEW

**Comment by TonyDroidd** [comment]
Patetic

**Comment by Pub4Game** [comment]
what?

**Comment by TonyDroidd** [comment]
You pull request is patetic

**Comment by Flavius12** [comment]
The Russian language has already been updated (I already fixed the "+" on the Russian language file)
Then plugin.yml and commands changes aren't needed.
Thanks anyway :)

**Comment by Pub4Game** [comment]
You yourself checked? The command /sa help to enter only OP! As players can view help?

**Comment by Flavius12** [comment]
You are right. I forgot the serverauth.help permission on plugin.yml.
Added to the To-Do list #14
Thank you!

**Pull request closed without merging**
