### PR TITLE
Major bug, since C-Mode does not count as Interact

### PR DESCRIPTION
**Pull request by legoboy0215**
This is tested. My server has been griefed due to this issue.

Also, PlayerMoveEvent addition: You can turn your head around, finally!

### CODE REVIEW

**Comment by Flavius12** [comment]
Can you be a bit more detailed?

**Comment by legoboy0215** [comment]
Basically, when the player is in c-mode when they joined, and has permission to break, they can break blocks even before they login.

**Comment by Flavius12** [comment]
Ah ok. I'll review your pull request when I'm a bit free

**Comment by legoboy0215** [comment]
Thanks.

**Comment by PEMapModder** [comment]
Correction:
PlayerInteractEvent is fired when a player long-clicks on any block, creative mode or not. It registers the start-breaking-time. If it is cancelled, server thinks that player started breaking block long-long-time-ago, explaining why it works on servers that don't set `BlockBreakEvent->setInstaBreak(true)`. However, creative mode is instabreak true, so it is not handled.
As for BlockPlaceEvent, I think PlayerInteractEvent helps. Make tests again to make sure that it should be explicitly cancelled?

**Comment by legoboy0215** [comment]
Oh! Sorry no ;) Only BlockBreakEvent.

**Comment by legoboy0215** [comment]
Done.

**Pull request closed without merging**
