### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by Pub4Game**
Fix a bug where players could break blocks are not logged

### CODE REVIEW

**Comment by Flavius12** [comment]
OMG. Did I really forget this event!?

**Comment by Pub4Game** [comment]
Yes :/

**Comment by legoboy0215** [comment]
LMAO

**Comment by PEMapModder** [comment]
PlayerInteractEvent should prevent that.

**Comment by Pub4Game** [comment]
@PEMapModder He doesn't do that :/

**Comment by PEMapModder** [comment]
?

**Comment by Pub4Game** [comment]
It is, so I added this event

**Comment by PEMapModder** [comment]
The problem is, PlayerInteractEvent is already cancelled, so this handler is reduce m redundant.

**Comment by Pub4Game** [comment]
Please check block breaking are not logged

**Comment by PEMapModder** [comment]
Logged?

**Comment by Pub4Game** [comment]
Ohh... authorized

**Comment by PEMapModder** [comment]
#59

**Comment by PEMapModder** [comment]
OK, this serves a purpose too. If BlockBreakEvent->setInstaBreak() is set to true, or if anticheats are disabled, this won't be checked.

**Comment by Pub4Game** [comment]
....

**Comment by alex2534alex** [comment]
Oh, just accept this pull!

**Pull request merged**
