### PR TITLE
Update EventListener.php

### PR DESCRIPTION
**Pull request by Pub4Game**

### CODE REVIEW

**Comment by Flavius12** [comment]
Does this work?

**Comment by Pub4Game** [comment]
No, I was wrong

**Comment by Flavius12** [comment]
As you can see it's a MCPE bug

**Comment by Pub4Game** [comment]
:(

**Comment by Pub4Game** [comment]
@Flavius12 It works! I just don't check

**Comment by Flavius12** [comment]
You are right :smiley: IT WORKS!
I'm adding this manually

**Comment by Pub4Game** [comment]
:((  But....

**Comment by Flavius12** [comment]
Fixed :+1:
See: https://github.com/EvolSoft/ServerAuth/blob/master/ServerAuth/src/ServerAuth/EventListener.php#L58
Thank you for report :smile:

**Pull request closed without merging**
