### PR TITLE
fix force-single-auth

### PR DESCRIPTION
**Pull request by Pub4Game**
You entered a wrong value! It will never be $count > 1

### CODE REVIEW

**Comment by Flavius12** [comment]
The _$count_ variable is the number of all players with the same name. Single authentication means that there can be maximum one player so if $count is greater than 1 other players with the same name will be kicked except the first one

**Comment by Pub4Game** [comment]
Oh no.... Check it out!!

**Comment by Pub4Game** [comment]
image

I badly know English, therefore, explained in the picture

**Comment by PEMapModder** [comment]
The 1 is the current player?

**Comment by Pub4Game** [comment]
@PEMapModder Just check for yourself... force-single-auth does not work!

**Comment by Flavius12** [comment]
@PEMapModder is right. $count contains the number of players with the same name of the player who joins. This means that if there is another player with a same name who is playing before, the $count variable will be: 1 (old player) + 1 (event player) = 2 and so greater than 1. The event player will be kicked.
Then $count++ means increment by one. It's a better looking way to write $count = $count + 1 or $count += 1.
I tested the function and it works for me.

**Comment by Pub4Game** [comment]
image

**Comment by Pub4Game** [comment]
image

After my changes

**Comment by Patra3** [comment]
That works. In your picture it is kicking whatever extra player is logging into your account, like it's supposed to.

**Comment by Flavius12** [comment]
What PocketMine build are you using @Pub4Game?

**Comment by Pub4Game** [comment]
@Flavius12 Doesn't work for me.... bleeding 48 PM

**Comment by PEMapModder** [comment]
What I know is this works :smile:
https://github.com/LegionPE/LegionPE-Theta-Base/blob/master/src/legionpe/theta/BaseListener.php#L52

**Comment by PEMapModder** [comment]
@Pub4Game to prove your theory, have you ensured that the third player gets kicked?

**Comment by legoboy0215** [comment]
...

**Comment by Pub4Game** [comment]
Lol... what I did is working correctly! It is tested on more than 30 servers in our hosting.

**Comment by Flavius12** [comment]
@Pub4Game seems to be right. I did some tests with Dev build 1269 and it works perfectly, then I tried with Bleeding build 48 and it seems not working. Is this a PocketMine bug or in newest PocketMine builds the player is added to the online players array after PreLoginEvent???
@Pub4Game if I change this part of code now I'll break compatibility with old PocketMine builds but if I don't do this, this feature may not work with newest builds. Keep in mind that PocketMine Bleeding is very unstable and this can be a PocketMine bug. So until I'm not sure that this is not a PM bug, I can't change this part of code

**Comment by legoboy0215** [comment]
@Pub4Game Yay! But why would this happen? Is this a brand-new unknown PM bug?

**Comment by Pub4Game** [comment]
Well. I just wanted to help

**Comment by Flavius12** [comment]
Yes and I **_must say a big thank you**_ because you reported a strange problem that must be considered. This means that when PocketMine Bleeding will become stable and if there is still this problem, I'll approve this pull-request.

**Comment by HotFireyDeath** [comment]
Create two separate releases?

**Pull request closed without merging**
