### PR TITLE
Fixes kicking the player who is already logged in.

### PR DESCRIPTION
**Pull request by Nivek-C94**
It also works if the player already connected is not logged in..will just kick the player trying to join. Im sure there is a better way to do this..but it works :p

### CODE REVIEW

**Comment by AndreyNazarchuk** [comment]
you guys should make a release already...

**Comment by PEMapModder** [comment]
Could you explain the one space indent?

**Comment by PEMapModder** [comment]
https://github.com/PEMapModder/HereAuth/blob/master/src/HereAuth/EventRouter.php#L74 might inspire you

**Comment by Flavius12** [comment]
Already fixed in v2.12

**Comment by Nivek-C94** [comment]
ah..mah bad didnt see there was a new version.

**Comment by Flavius12** [comment]
https://github.com/EvolSoft/ServerAuth/releases/tag/v2.12

**Pull request closed without merging**
